[editor]
scrolloff = 5
line-number = "relative"
rulers = [80, 120]
idle-timeout = 300
completion-timeout = 50
shell = ["zsh", "-c"]

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = true
display-color-swatches = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true
display-inlay-hints = true
auto-signature-help = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]

center = ["diagnostics"]
right = ["position", "file-encoding", "file-type"]
mode.normal = "N"
mode.insert = "I"
mode.select = "V"

[keys.insert]
"C-[" = "normal_mode"
